version: '3'
services:
  empty-legacy-mssql:
    build: src/RoadRegistry.LegacyDatabase/empty
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'E@syP@ssw0rd'
      MSSQL_MEMORY_LIMIT_MB: 1000
    ports:
      - "41433:1433"
    volumes:
      - empty-legacy-mssql-data:/var/opt/mssql
      - ./src/RoadRegistry.LegacyDatabase/empty:/var/lib/backup
  empty-legacystreamextraction:
    build: dist/RoadRegistry.LegacyStreamExtraction/linux
    depends_on:
      - empty-legacy-mssql
    environment:
      BLOBCLIENTTYPE: FileBlobClient
      FILEBLOBCLIENTOPTIONS__OUTPUTDIRECTORY: /var/lib/RoadRegistry.LegacyStreamExtraction/output
      LEGACYSQLDATABASEOPTIONS__CONNECTIONSTRINGNAME: Legacy
      CONNECTIONSTRINGS__LEGACY: Data Source=tcp:empty-legacy-mssql,1433;Initial Catalog=LegacyRoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
    volumes:
      - ./src/RoadRegistry.LegacyStreamExtraction:/var/lib/RoadRegistry.LegacyStreamExtraction
  filled-legacy-mssql:
    build: src/RoadRegistry.LegacyDatabase/filled
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'E@syP@ssw0rd'
      MSSQL_MEMORY_LIMIT_MB: 1000
    ports:
      - "31433:1433"
    volumes:
      - filled-legacy-mssql-data:/var/opt/mssql
      - ./src/RoadRegistry.LegacyDatabase/filled:/var/lib/backup
  filled-legacystreamextraction:
    build: dist/RoadRegistry.LegacyStreamExtraction/linux
    depends_on:
      - filled-legacy-mssql
    environment:
      BLOBCLIENTTYPE: FileBlobClient
      FILEBLOBCLIENTOPTIONS__OUTPUTDIRECTORY: /var/lib/RoadRegistry.LegacyStreamExtraction/output
      LEGACYSQLDATABASEOPTIONS__CONNECTIONSTRINGNAME: Legacy
      CONNECTIONSTRINGS__LEGACY: Data Source=tcp:legacy-mssql,1433;Initial Catalog=LegacyRoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
    volumes:
      - ./src/RoadRegistry.LegacyStreamExtraction:/var/lib/RoadRegistry.LegacyStreamExtraction
  mssql:
    build: src/RoadRegistry.Database
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'E@syP@ssw0rd'
      MSSQL_MEMORY_LIMIT_MB: 4000
    ports:
      - "21433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
  legacystreamloader:
    build: dist/RoadRegistry.LegacyStreamLoader/linux
    depends_on:
      - mssql
    environment:
      BLOBCLIENTTYPE: FileBlobClient
      FILEBLOBCLIENTOPTIONS__INPUTDIRECTORY: /var/lib/RoadRegistry.LegacyStreamExtraction/output
      EVENTSQLDATABASEOPTIONS__CONNECTIONSTRINGNAME: Events
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
    volumes:
      - ./src/RoadRegistry.LegacyStreamExtraction:/var/lib/RoadRegistry.LegacyStreamExtraction
  projectionhost:
    build: dist/RoadRegistry.BackOffice.Projections/linux
    depends_on:
      - mssql
    environment:
      CONNECTIONSTRINGS__BLOBS: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__SHAPEPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__SHAPEPROJECTIONSADMIN: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
  eventhost:
    build: dist/RoadRegistry.BackOffice.EventHost/linux
    depends_on:
      - mssql
    environment:
      CONNECTIONSTRINGS__BLOBS: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__EVENTHOST: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__EVENTHOSTADMIN: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
  commandhost:
    build: dist/RoadRegistry.BackOffice.CommandHost/linux
    depends_on:
      - mssql
    environment:
      CONNECTIONSTRINGS__BLOBS: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__COMMANDHOST: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__COMMANDHOSTADMIN: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
  api:
    build: dist/RoadRegistry.BackOffice.Api/linux
    depends_on:
      - mssql
      - projectionhost
    environment:
      CONNECTIONSTRINGS__BLOBS: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__BLOBSADMIN: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__SHAPEPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      CONNECTIONSTRINGS__SHAPEPROJECTIONSADMIN: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
      IDEMPOTENCY__CONNECTIONSTRING: Data Source=tcp:mssql,1433;Initial Catalog=RoadRegistry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;
    ports:
      - "5020:5000"
  ui:
    build: dist/RoadRegistry.UI/linux
    depends_on:
      - api
    environment:
      API__ENDPOINT: http://localhost:5020
    ports:
      - "5010:5000"
volumes:
  mssql-data:
  filled-legacy-mssql-data:
  empty-legacy-mssql-data:
